### PR TITLE
Feature/historic count data

### LINKED ISSUE #79: Process historical bike count data
Process bike count data from excel file to JSON, and create api endpoint

### PR DESCRIPTION
**Pull request by jorensjongers**
Fixes oSoc19/cycling-up-frontend#79

## Description

- Added new source GeoJSON file with count locations and count data as a property.
--QUESTION: script to generate this GeoJSON file from a .csv file is also added, but has no further use for the API. What should I do with this?

- Added new API route to query this data.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
- [ ] ID requested to the back-end should match Live API (see <https://data-mobility.brussels/bike/api/counts/?request=live>)
- [ ] Locations are available in "Fietstelling" layer from Mobigis, it should come from there during the "process data" process
- [ ] "process data" process should convert the CSV from Excel sheet to GeoJSON

**Comment by jorensjongers** [comment]
@jbelien 

**1) concerning matching the IDs to mobiles live data**
I considered doing this, but unfortunately these are not the same data.
The historic data is obtained through human counters that count all bicycles entering a certain square/crossroads/... during one hour of the day (between 8PM and 9PM) one 4 days per year.
The live data is obtained through counting machines. And only count bicycles that are registered by these machines. They are operational throughout the day, all year round. 

**2) concerning retrieving locations from mobigis**
The counting locations from the historic (human) counts and the live (machine) counts only rarely match. Also they represented a different way of counting as explained above.

**Comment by jbelien** [comment]
Okay, thanks for the explanation!

Just fix the Excel > CSV > GeoJSON process then! 👍

**Comment by jorensjongers** [comment]
@jbelien 

**3) concerning the process_data**
I discussed this with @Dakad and he will fix this in another issue:
oSoc19/cycling-up-frontend#97

**Review by jbelien — APPROVED** [review]

**Pull request merged**
